application:
    name: "@project.artifactId@"
    version: "@project.version@"
    timezone: Asia/Makassar
    allowed-origins: 
        - http://localhost:8000
    access-token:
        public-key-path: cert/access.pub
        private-key-path: cert/access.priv
        expiration: 15m
    refresh-token:
        public-key-path: cert/refresh.pub
        private-key-path: cert/refresh.priv
        expiration: 7d

logging:
    file:
        path: logs
        name: form-log.jsonl
    level:
        org:
            hibernate: error
        root: info
server:
    port: 8000

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/yours_form
        username: root
        password: root
        hikari:
            connection-timeout: 10000
            idle-timeout: 120000
            maximum-pool-size: 20
            minimum-idle: 2
    flyway:
        enabled: true
    web:
        resources:
            add-mappings: false
    messages:
        basename: locale/messages
        encoding: UTF-8
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                "[default_schema]": satu_sehat
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": false
        show-sql: false
