application:
    name: "@project.artifactId@"
    version: "@project.version@"
    timezone: Asia/Makassar
    token:
        access:
            public-key-path: classpath:token/access-public-key
            private-key-path: classpath:token/access-private-key.priv
            expiration: 15m
        refresh:
            public-key-path: classpath:token/refresh-public-key
            private-key-path: classpath:token/refresh-private-key.priv
            expiration: 7d
logging:
    file:
        path: logs
        name: form-log.jsonl
    level:
        org:
            hibernate: error
        root: info
server:
    port: 8000
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/yours_form
        username: root
        password: root
        hikari:
            connection-timeout: 10000
            idle-timeout: 120000
            maximum-pool-size: 20
            minimum-idle: 2
    flyway:
        enabled: true
    web:
        resources:
            add-mappings: false
        locale: id_ID
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                "[default_schema]": satu_sehat
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": false
        show-sql: false
